apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: poststart
spec:
  secretsName: my-cluster-secrets
  sslSecretName: some-name-ssl
  pxc:
    size: 3
    image: -pxc
    lifecycle:
      postStart:
        exec:
          command: ["/bin/true"]
    resources:
      requests:
        memory: 1G
        cpu: 600m
      limits:
        memory: "1G"
        cpu: "1"
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2Gi
  proxysql:
    enabled: true
    size: 1
    image: -proxysql
    lifecycle:
      postStart:
        exec:
          command: ["/bin/true"]
    resources:
      requests:
        memory: 1G
        cpu: 600m
      limits:
        memory: 1G
        cpu: 700m
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2Gi
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
  pmm:
    enabled: false
    image: perconalab/pmm-client:1.17.1
    serverHost: monitoring-service
    serverUser: pmm
